gaofei.local:
 default_locale: 'cn'
 ip: 192.168.1.200
 port: 3001
 account_server_ip: 192.168.1.200
 account_server_port: 3000
 info_const_version: 12
 env: dev
 redis:
  host: 127.0.0.1
  port: 16379
  drvier: 'hiredis'
  db: 0

ali001:
 default_locale: 'cn'
 ip: 42.120.23.41
 port: 10002
 account_server_ip: 42.120.23.41
 account_server_port: 10001
 info_const_version: 12
 env: production
 redis:
  host: 127.0.0.1
  port: 16379
  drvier: 'hiredis'
  db: 0