gaofei.local:
 ip: 192.168.1.200
 port: 3001
 account_server_ip: 106.187.91.156
 account_server_port: 10001
 info_const_version: 12
 env: dev
 redis:
  host: 127.0.0.1
  port: 6379

dinotest:
 ip: 106.187.91.156
 port: 10002
 account_server_ip: 106.187.91.156
 account_server_port: 10001
 info_const_version: 12
 env: dev
 redis:
  host: 127.0.0.1
  port: 6379

a001:
 ip: 50.112.84.136
 port: 10002
 account_server_ip: 50.112.84.136
 account_server_port: 10001
 info_const_version: 12
 env: production
 redis:
  host: 127.0.0.1
  port: 6379

ali001:
 ip: 42.120.23.41
 port: 10002
 account_server_ip: 50.112.84.136
 account_server_port: 10001
 info_const_version: 12
 env: production
 redis:
  host: 127.0.0.1
  port: 6379
