gaofei.local:
 ip: 192.168.1.200
 port: 3001
 account_server_ip: 106.187.91.156
 account_server_port: 10001
 info_const_version: 5
 env: dev
 redis:
  host: 192.168.1.200
  port: 6379


dinotest:
 ip: 106.187.91.156
 port: 10002
 account_server_ip: 106.187.91.156
 account_server_port: 10001
 info_const_version: 9
 env: dev

a001:
 ip: 50.112.84.136
 port: 10002
 account_server_ip: 50.112.84.136
 account_server_port: 10001
 info_const_version: 9
 env: production