gaofei.local:
 ip: 192.168.1.200
 port: 3001
 account_server_ip: 192.168.1.200
 account_server_port: 3000
 info_const_version: 13

dinotest:
 ip: 106.187.91.156
 port: 10002
 account_server_ip: 106.187.91.156
 account_server_port: 10001
 info_const_version: 13