gaofei.local:
 ip: 192.168.1.200
 port: 3001
 account_server_ip: 192.168.1.200
 account_server_port: 3000
 info_const_version: 17
 env: dev

dinotest:
 ip: 106.187.91.156
 port: 10002
 account_server_ip: 50.112.84.136
 account_server_port: 10001
 info_const_version: 17
 env: dev

a001:
 ip: 50.112.84.136
 port: 10002
 account_server_ip: 50.112.84.136
 account_server_port: 10001
 info_const_version: 17
 env: prod